PIs:
  1:
    enabled: true
    controller: true
    ip: 192.168.1.7
  2:
    enabled: false
    controller: true
    ip: null
  3:
    enabled: false
    controller: true
    ip: null

COSMO:
  ip: 192.168.1.6

switches:
  1: 
    Name: Nox Fill
    Pi: 1
    Relay: 1
  2:
    Name: Nox Vent
    Pi: 1
    Relay: 2
  3:
    Name: Nox Relief
    Pi: 1
    Relay: 3
  4:
    Name: Nitrogen Fill
    Pi: 1
    Relay: 4
  5:
    Name: Nitrogen Vent
    Pi: 1
    Relay: 5
  6:
    Name: Continuity
    Pi: 1
    Relay: 6
  7:
    Name: null
    Pi: null
    Relay: null
  8:
    Name: null
    Pi: null
    Relay: null
  9:
    Name: null
    Pi: null
    Relay: null
  10:
    Name: null
    Pi: null
    Relay: null
  enable_fire:
    Pi: 1
    Relay: 7
  fire:
    Pi: 1
    Relay: 8
  abort:
    Pi: null
    Relay: null