PIs:
  controller:
    enabled: true
    ip: 192.168.1.30
    relays:
      1:
        name: Nox Fill
        switch: 1
      2:
        name: Nox Vent
        switch: 2
      3:
        name: Nox Relief
        switch: 3
      4:
        name: Nitrogen Fill
        switch: 4
      5:
        name: Nitrogen Vent
        switch: 5
      6:
        name: Continuity
        switch: 6
      7:
        name: ENABLE FIRE
        switch: ENABLE FIRE
      8:
        name: FIRE
        switch: FIRE

  1:
    enabled: true
    ip: 192.168.1.31
    relays:
      1:
        name: null
        switch: null
      2:
        name: null
        switch: null
      3:
        name: null
        switch: null
      4:
        name: null
        switch: null
      5:
        name: null
        switch: null
      6:
        name: null
        switch: null
      7:
        name: null
        switch: null
      8:
        name: null
        switch: null

  2:
    enabled: false
    ip: 192.168.1.32
    relays:
      1:
        name: null
        switch: null
      2:
        name: null
        switch: null
      3:
        name: null
        switch: null
      4:
        name: null
        switch: null
      5:
        name: null
        switch: null
      6:
        name: null
        switch: null
      7:
        name: null
        switch: null
      8:
        name: null
        switch: null
    

COSMO:
  ip: 192.168.1.6
