PIs:
  controller:
    enabled: true
    ip: 192.168.1.30
    relays:
      1:
        name: Nox Fill
        switch: 1
      2:
        name: Nox Vent
        switch: 2
      3:
        name: N2 Fill
        switch: 6
      4:
        name: N2 Vent
        switch: 7
      5:
        name: Servo Power
        switch: 9
      6:
        name: ARM 1
        switch: ENABLE FIRE
      7:
        name: ARM 2
        switch: ENABLE FIRE
      8:
        name: FIRE
        switch: FIRE

  1:
    enabled: true
    ip: 192.168.1.31
    relays:
      1:
        name: Fuel Main  # Will be used in timing
        switch: 5
      2:
        name: NOX Main # will be used in timing
        switch: 5
      3:
        name: Fuel/N2 Relief
        switch: 8
      4:
        name: NOX Relief
        switch: 3
      5:
        name: Servo Move
        switch: 10
      6:
        name: Dome Vent
        switch: 4
      7:
        name: null
        switch: null
      8:
        name: null
        switch: null

  2:
    enabled: false
    ip: 192.168.1.32
    relays:
      1:
        name: null
        switch: null
      2:
        name: null
        switch: null
      3:
        name: null
        switch: null
      4:
        name: null
        switch: null
      5:
        name: null
        switch: null
      6:
        name: null
        switch: null
      7:
        name: null
        switch: null
      8:
        name: null
        switch: null


COSMO:
  ip: 192.168.1.8
