PIs:
  contoller:
    enabled: true
    ip: 192.168.1.7
    relays:
      1:
        name: Nox Fill
        switch: 1
      2:
        name: Nox Vent
        switch: 2
      3:
        name: Nox Relief
        switch: 3
      4:
        name: Nitrogen Fill
        switch: 4
      5:
        name: Nitrogen Vent
        switch: 5
      6:
        name: Continuity
        switch: 6
      7:
        name: ENABLE FIRE
        switch: ENABLE FIRE
      8:
        name: FIRE
        switch: FIRE

  1:
    enabled: false
    ip: null

  2:
    enabled: false
    ip: null

COSMO:
  ip: 192.168.1.6
